services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@envios_high?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=SPRINGBOOT_USER
      - SPRING_DATASOURCE_PASSWORD=Springboot123
      - TNS_ADMIN=/app/wallet
    volumes:
      - ./src/main/resources/wallet:/app/wallet:ro